# Generated by Django 5.0 on 2026-03-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, help_text="User's email address", max_length=150, unique=True, verbose_name='Email Field'),
        ),
    ]
